
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-11
owner: ucsb-cs156-f24
repo_name: team01-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2NDQ1ODIz","is_bot":false,"login":"brianc2730","name":"Brian Cheng"},"headRefName":"Brian-RecommendationRequest-Create-Controller","number":54,"title":"Brian - Recommendation Request Create Controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/54"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-get","number":53,"title":"Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/53"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"Jonathan-HelpRequest","number":50,"title":"Entity and Repository","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/50"}]
