
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-11
owner: ucsb-cs156-f24
repo_name: team01-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MTEzMzIw","is_bot":false,"login":"JohnLins","name":"John Lins"},"headRefName":"John-MenuItemTable","number":45,"title":"Completed task: add links and update title","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/45"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-ArticleTable","number":44,"title":"Frank article table","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/44"}]
