
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-11
owner: ucsb-cs156-f24
repo_name: team01-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-createTable","number":49,"title":"finished 2nd task","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/49"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam/createTable","number":48,"title":"Create database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team01-f24-11/pull/48"}]
